/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJsonMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrometheusMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadOpenApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setSessionToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clearSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listAccounts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getPortfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getAnalytics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeatureFlags"];
        put?: never;
        post: operations["updateFeatureFlags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feature-flags/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetFeatureFlags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistoryMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHistorySnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHistoryEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAlertRules"];
        put?: never;
        post: operations["createAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAlertRule"];
        options?: never;
        head?: never;
        patch: operations["patchAlertRule"];
        trace?: never;
    };
    "/api/alerts/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAlertNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runAlertCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enqueueAnalyticsJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createOrUpdateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assignUserAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeUserAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSloSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OkResponse: {
            ok: boolean;
        };
        ErrorResponse: {
            error: string;
            requestId?: string;
            /** @description Additional details, shape depends on endpoint. */
            details?: unknown;
        };
        HealthResponse: {
            ok: boolean;
        };
        MetricsResponse: {
            uptimeSec: number;
            totalRequests: number;
            byStatus: {
                [key: string]: number;
            };
            byRoute: {
                [key: string]: number;
            };
        };
        SessionStatusResponse: {
            ok: boolean;
            hasToken: boolean;
        };
        SessionTokenRequest: {
            token: string;
        };
        AccountsRequest: {
            token?: string;
        };
        AccountScopedRequest: {
            token?: string;
            accountId: string;
        };
        AccountsResponse: {
            accounts?: {
                id?: string;
                name?: string;
                type?: string;
                status?: string;
            }[];
        };
        PortfolioResponse: {
            total: string;
            positions: {
                [key: string]: unknown;
            }[];
            moverPositions: {
                [key: string]: unknown;
            }[];
        };
        AnalyticsResponse: {
            currency: string;
            total: string;
            profitRub: string;
            profitValue?: number;
            profitPct: string;
            yieldPct?: string;
            assetPie: {
                [key: string]: unknown;
            }[];
            assetBreakdown?: {
                [key: string]: unknown;
            }[];
            myAssets?: {
                [key: string]: unknown;
            }[];
            myAssetsTotals?: {
                [key: string]: unknown;
            };
            incomeNext12: {
                [key: string]: unknown;
            }[];
            receivedDividends12?: {
                [key: string]: unknown;
            }[];
            redemptionsNext12?: {
                [key: string]: unknown;
            }[];
            upcomingEvents: {
                [key: string]: unknown;
            }[];
        };
        FeatureFlags: {
            native_ui_default: boolean;
            session_auth_required: boolean;
            background_analytics_jobs: boolean;
            reports_export_enabled: boolean;
            alerts_enabled: boolean;
            rbac_enabled: boolean;
        };
        HistoryMeta: {
            snapshots: number;
            events: number;
            /** Format: date-time */
            updatedAt: string;
        };
        HistorySnapshot: {
            id: string;
            accountId: string;
            /** @enum {string} */
            source: "portfolio" | "analytics";
            /** Format: date-time */
            capturedAt: string;
            dateKey: string;
            totalText: string;
            totalValue: number;
            profitValue?: number;
            yieldPct?: number;
            currency?: string;
        };
        HistoryEvent: {
            id: string;
            accountId: string;
            eventType: string;
            title: string;
            details?: string;
            /** @description Arbitrary event payload. */
            payload?: unknown;
            /** Format: date-time */
            createdAt: string;
        };
        AlertRule: {
            id: string;
            name: string;
            accountId?: string;
            /** @enum {string} */
            metric: "total_value" | "profit_value" | "yield_pct";
            /** @enum {string} */
            operator: "lt" | "lte" | "gt" | "gte";
            threshold: number;
            /** @enum {string} */
            severity: "info" | "warn" | "critical";
            /** @enum {string} */
            channel: "log" | "webhook" | "email" | "telegram";
            enabled: boolean;
            cooldownMinutes: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            lastTriggeredAt?: string;
        };
        AlertRuleCreateRequest: {
            name: string;
            accountId?: string;
            /** @enum {string} */
            metric: "total_value" | "profit_value" | "yield_pct";
            /** @enum {string} */
            operator: "lt" | "lte" | "gt" | "gte";
            threshold: number;
            /** @enum {string} */
            severity?: "info" | "warn" | "critical";
            /** @enum {string} */
            channel?: "log" | "webhook" | "email" | "telegram";
            enabled?: boolean;
            cooldownMinutes?: number;
        };
        AlertNotification: {
            id: string;
            ruleId: string;
            accountId: string;
            /** @enum {string} */
            severity: "info" | "warn" | "critical";
            /** @enum {string} */
            channel: "log" | "webhook" | "email" | "telegram";
            title: string;
            message: string;
            value: number;
            threshold: number;
            /** Format: date-time */
            createdAt: string;
            delivered: boolean;
        };
        BackgroundJob: {
            id: string;
            /** @enum {string} */
            type: "analytics_report";
            accountId: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            error?: string;
            result?: {
                [key: string]: unknown;
            };
        };
        UserRecord: {
            id: string;
            /** @enum {string} */
            role: "viewer" | "editor" | "admin";
            accounts: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserUpsertRequest: {
            id: string;
            /** @enum {string} */
            role?: "viewer" | "editor" | "admin";
            accounts?: string[];
        };
        SloSnapshot: {
            objectivePct: number;
            availabilityPct: number;
            successRequests: number;
            totalRequests: number;
            errorBudgetPct: number;
            consumedErrorBudgetPct: number;
            burnRate: number;
            healthy: boolean;
        };
    };
    responses: {
        /** @description API error response. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        accountIdQuery: string;
        limitQuery: number;
        ruleIdPath: string;
        userIdPath: string;
        accountIdPath: string;
        jobIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getJsonMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON metrics snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    getPrometheusMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus exposition format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    downloadOpenApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI YAML spec. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current browser session status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusResponse"];
                };
            };
        };
    };
    setSessionToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionTokenRequest"];
            };
        };
        responses: {
            /** @description Session token updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    clearSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session token removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AccountsRequest"];
            };
        };
        responses: {
            /** @description Broker account list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            502: components["responses"]["ErrorResponse"];
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountScopedRequest"];
            };
        };
        responses: {
            /** @description Aggregated portfolio response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            502: components["responses"]["ErrorResponse"];
        };
    };
    getAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountScopedRequest"];
            };
        };
        responses: {
            /** @description Extended analytics response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            502: components["responses"]["ErrorResponse"];
        };
    };
    getFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime feature flags. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        flags: components["schemas"]["FeatureFlags"];
                    };
                };
            };
        };
    };
    updateFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: boolean;
                };
            };
        };
        responses: {
            /** @description Updated runtime feature flags. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        flags: components["schemas"]["FeatureFlags"];
                    };
                };
            };
            403: components["responses"]["ErrorResponse"];
        };
    };
    resetFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime overrides dropped. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        flags: components["schemas"]["FeatureFlags"];
                    };
                };
            };
            403: components["responses"]["ErrorResponse"];
        };
    };
    getHistoryMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History storage metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryMeta"];
                };
            };
        };
    };
    listHistorySnapshots: {
        parameters: {
            query?: {
                accountId?: components["parameters"]["accountIdQuery"];
                limit?: components["parameters"]["limitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical portfolio snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accountId?: string | null;
                        items: components["schemas"]["HistorySnapshot"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    listHistoryEvents: {
        parameters: {
            query?: {
                accountId?: components["parameters"]["accountIdQuery"];
                limit?: components["parameters"]["limitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical timeline events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accountId?: string | null;
                        items: components["schemas"]["HistoryEvent"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    listAlertRules: {
        parameters: {
            query?: {
                accountId?: components["parameters"]["accountIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured alert rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AlertRule"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    createAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreateRequest"];
            };
        };
        responses: {
            /** @description Alert rule created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    deleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ruleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    patchAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ruleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Updated alert rule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listAlertNotifications: {
        parameters: {
            query?: {
                accountId?: components["parameters"]["accountIdQuery"];
                limit?: components["parameters"]["limitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert notifications timeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AlertNotification"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    runAlertCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountScopedRequest"];
            };
        };
        responses: {
            /** @description Alert checks completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        created: components["schemas"]["AlertNotification"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                accountId?: components["parameters"]["accountIdQuery"];
                limit?: components["parameters"]["limitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Background jobs queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["BackgroundJob"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    enqueueAnalyticsJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountScopedRequest"];
            };
        };
        responses: {
            /** @description Job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackgroundJob"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    getJobById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Background job details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackgroundJob"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RBAC users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UserRecord"][];
                    };
                };
            };
            403: components["responses"]["ErrorResponse"];
        };
    };
    createOrUpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpsertRequest"];
            };
        };
        responses: {
            /** @description User saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecord"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    assignUserAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accountId: string;
                };
            };
        };
        responses: {
            /** @description Account granted to user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecord"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    revokeUserAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userIdPath"];
                accountId: components["parameters"]["accountIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account revoked from user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecord"];
                };
            };
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    exportReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accountId: string;
                    /** @enum {string} */
                    format: "json" | "xlsx" | "pdf";
                };
            };
        };
        responses: {
            /** @description Generated report payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            400: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    getSloSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SLO and error budget snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SloSnapshot"];
                };
            };
        };
    };
}
